# Generated by Django 6.0.4 on 2026-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('companion', models.CharField(max_length=50)),
                ('year_range', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('poster_url', models.TextField(blank=True)),
            ],
        ),
    ]
